name = "nav"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "NAV_DB"
database_name = "book"
database_id = "d23399a6-d5d1-4a7a-851b-c5212a0ffb88"

[[kv_namespaces]]
binding = "NAV_AUTH"
id = "2f2535ec934a448cb39f027830864c40"
