// 构建首页 CSS：用 Tailwind CLI 按 content 扫描生成被实际用到的样式，
// 再拼接首页自定义样式（home-custom.css），最终包装成 JS 字符串常量供 Worker 直接 import。
//
// 运行：node scripts/build-css.mjs（已接入 npm run build:css，并前置于 dev / deploy）。
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const INPUT = 'src/styles/input.css';
const CUSTOM = 'src/styles/home-custom.css';
const OUT = 'src/pages/home/generated-css.js';

const tmpFile = join(mkdtempSync(join(tmpdir(), 'starnav-css-')), 'out.css');

execSync(
  `npx tailwindcss -c tailwind.config.cjs -i ${INPUT} -o "${tmpFile}" --minify`,
  { stdio: 'inherit' },
);

const tailwindCss = readFileSync(tmpFile, 'utf8').trim();
const customCss = readFileSync(CUSTOM, 'utf8').trim();
// 自定义样式排在 utilities 之后，确保对 Tailwind 生成类的覆盖生效（与原内联顺序一致）。
const finalCss = `${tailwindCss}\n${customCss}`;

writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/build-css.mjs — 请勿手动编辑。运行 npm run build:css 重新生成。\nexport const homeCss = ${JSON.stringify(finalCss)};\n`,
);

console.log(`已生成 ${OUT}：${finalCss.length} 字节 CSS（tailwind ${tailwindCss.length} + custom ${customCss.length}）。`);
